name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  sanity:
    name: Sanity (${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        package-storage-ref: ["production"]

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Checkout assets
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ matrix.package-storage-ref }}
          path: assets/${{ matrix.package-storage-ref }}

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make tests

      - name: Sanity checks
        run: make sanity
