name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  package-sanity:
    name: Python package sanity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: make prereq

      - name: Build package
        run: make pkg-build

      - name: Check sanity
        run: make pkg-sanity
